import type { ShopItem, TechnicianItem, CustomerItem, OrderItem, PlatformOverview, RevenueAnalytics, NotificationItem } from '../types/admin';

export const mockShops: ShopItem[] = [
  {
    _id: 'shop_01',
    name: 'OK-Repair Solutions',
    ownerName: 'Sunil Verma',
    phone: '9876543210',
    address: { street: 'Shop 14, Galaxy Market, Andheri East', city: 'Mumbai', state: 'Maharashtra', pincode: '400069' },
    subscription: { plan: 'pro', status: 'active', expiresAt: new Date(Date.now() + 86400000 * 180).toISOString() },
    settings: { currency: 'INR', smsNotificationsEnabled: true, nextJobNumber: 1045 },
    stats: { totalOrders: 28, totalRevenue: 64200, totalDues: 8400, totalStaff: 3, totalCustomers: 22 },
    createdAt: new Date(Date.now() - 86400000 * 90).toISOString(),
  },
  {
    _id: 'shop_02',
    name: 'TechZone Mobile & Laptop Care',
    ownerName: 'Deepak Patel',
    phone: '9822334455',
    address: { street: '42 Ring Road, Near Surat Station', city: 'Surat', state: 'Gujarat', pincode: '395003' },
    subscription: { plan: 'pro', status: 'active', expiresAt: new Date(Date.now() + 86400000 * 90).toISOString() },
    settings: { currency: 'INR', smsNotificationsEnabled: true, nextJobNumber: 2028 },
    stats: { totalOrders: 19, totalRevenue: 41800, totalDues: 6200, totalStaff: 2, totalCustomers: 17 },
    createdAt: new Date(Date.now() - 86400000 * 60).toISOString(),
  },
  {
    _id: 'shop_03',
    name: 'iFix Tech Lab',
    ownerName: 'Arun Krishnan',
    phone: '9744112233',
    address: { street: '88 100ft Road, Indiranagar', city: 'Bengaluru', state: 'Karnataka', pincode: '560038' },
    subscription: { plan: 'free', status: 'active' },
    settings: { currency: 'INR', smsNotificationsEnabled: true, nextJobNumber: 3012 },
    stats: { totalOrders: 12, totalRevenue: 28500, totalDues: 3100, totalStaff: 2, totalCustomers: 11 },
    createdAt: new Date(Date.now() - 86400000 * 45).toISOString(),
  },
  {
    _id: 'shop_04',
    name: 'RapidFix Electronics',
    ownerName: 'Manoj Sharma',
    phone: '9911223344',
    address: { street: 'G-7 Nehru Place', city: 'New Delhi', state: 'Delhi', pincode: '110019' },
    subscription: { plan: 'pro', status: 'active', expiresAt: new Date(Date.now() + 86400000 * 300).toISOString() },
    settings: { currency: 'INR', smsNotificationsEnabled: true, nextJobNumber: 4050 },
    stats: { totalOrders: 34, totalRevenue: 89000, totalDues: 11500, totalStaff: 3, totalCustomers: 29 },
    createdAt: new Date(Date.now() - 86400000 * 120).toISOString(),
  },
];

export const mockTechnicians: TechnicianItem[] = [
  {
    _id: 'tech_01',
    shopId: { _id: 'shop_01', name: 'OK-Repair Solutions', phone: '9876543210', address: { city: 'Mumbai' } },
    name: 'Rohan Deshmukh',
    phone: '9811002233',
    role: 'technician',
    isActive: true,
    activeJobsCount: 3,
    createdAt: new Date(Date.now() - 86400000 * 80).toISOString(),
  },
  {
    _id: 'tech_02',
    shopId: { _id: 'shop_01', name: 'OK-Repair Solutions', phone: '9876543210', address: { city: 'Mumbai' } },
    name: 'Vikas Kadam',
    phone: '9822114455',
    role: 'technician',
    isActive: true,
    activeJobsCount: 2,
    createdAt: new Date(Date.now() - 86400000 * 75).toISOString(),
  },
  {
    _id: 'tech_03',
    shopId: { _id: 'shop_01', name: 'OK-Repair Solutions', phone: '9876543210', address: { city: 'Mumbai' } },
    name: 'Sneha Patil',
    phone: '9833225566',
    role: 'staff',
    isActive: true,
    activeJobsCount: 0,
    createdAt: new Date(Date.now() - 86400000 * 70).toISOString(),
  },
  {
    _id: 'tech_04',
    shopId: { _id: 'shop_02', name: 'TechZone Mobile & Laptop Care', phone: '9822334455', address: { city: 'Surat' } },
    name: 'Jignesh Shah',
    phone: '9844336677',
    role: 'technician',
    isActive: true,
    activeJobsCount: 4,
    createdAt: new Date(Date.now() - 86400000 * 55).toISOString(),
  },
  {
    _id: 'tech_05',
    shopId: { _id: 'shop_02', name: 'TechZone Mobile & Laptop Care', phone: '9822334455', address: { city: 'Surat' } },
    name: 'Bhavesh Parmar',
    phone: '9855447788',
    role: 'technician',
    isActive: false,
    activeJobsCount: 1,
    createdAt: new Date(Date.now() - 86400000 * 50).toISOString(),
  },
  {
    _id: 'tech_06',
    shopId: { _id: 'shop_03', name: 'iFix Tech Lab', phone: '9744112233', address: { city: 'Bengaluru' } },
    name: 'Karthik Rao',
    phone: '9733221100',
    role: 'technician',
    isActive: true,
    activeJobsCount: 2,
    createdAt: new Date(Date.now() - 86400000 * 40).toISOString(),
  },
  {
    _id: 'tech_07',
    shopId: { _id: 'shop_04', name: 'RapidFix Electronics', phone: '9911223344', address: { city: 'New Delhi' } },
    name: 'Amit Tyagi',
    phone: '9922334411',
    role: 'technician',
    isActive: true,
    activeJobsCount: 3,
    createdAt: new Date(Date.now() - 86400000 * 110).toISOString(),
  },
];

export const mockCustomers: CustomerItem[] = [
  {
    _id: 'cust_01',
    shopId: { _id: 'shop_01', name: 'OK-Repair Solutions' },
    name: 'Amit Sharma',
    phone: '9823456781',
    email: 'amit.sharma@gmail.com',
    address: 'B-12, Sector 18, Noida',
    totalOrdersCount: 3,
    createdAt: new Date(Date.now() - 86400000 * 60).toISOString(),
  },
  {
    _id: 'cust_02',
    shopId: { _id: 'shop_01', name: 'OK-Repair Solutions' },
    name: 'Pooja Patel',
    phone: '9712345678',
    email: 'pooja.p@yahoo.com',
    address: 'A-45, Ring Road, Surat',
    totalOrdersCount: 2,
    createdAt: new Date(Date.now() - 86400000 * 50).toISOString(),
  },
  {
    _id: 'cust_03',
    shopId: { _id: 'shop_01', name: 'OK-Repair Solutions' },
    name: 'Rahul Mehta',
    phone: '9988776655',
    address: '104, Sunrise Heights, Mumbai',
    totalOrdersCount: 4,
    createdAt: new Date(Date.now() - 86400000 * 80).toISOString(),
  },
  {
    _id: 'cust_04',
    shopId: { _id: 'shop_02', name: 'TechZone Mobile & Laptop Care' },
    name: 'Hardik Trivedi',
    phone: '9877665544',
    email: 'hardik.t@outlook.com',
    address: 'Bhatar Road, Surat',
    totalOrdersCount: 2,
    createdAt: new Date(Date.now() - 86400000 * 45).toISOString(),
  },
  {
    _id: 'cust_05',
    shopId: { _id: 'shop_02', name: 'TechZone Mobile & Laptop Care' },
    name: 'Neha Singhania',
    phone: '9866554433',
    address: 'Ghod Dod Road, Surat',
    totalOrdersCount: 1,
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    _id: 'cust_06',
    shopId: { _id: 'shop_03', name: 'iFix Tech Lab' },
    name: 'Sanjay Reddy',
    phone: '9755443322',
    email: 'sanjay.r@gmail.com',
    address: 'Koramangala 4th Block, Bengaluru',
    totalOrdersCount: 2,
    createdAt: new Date(Date.now() - 86400000 * 35).toISOString(),
  },
  {
    _id: 'cust_07',
    shopId: { _id: 'shop_04', name: 'RapidFix Electronics' },
    name: 'Vikram Choudhary',
    phone: '9933445566',
    address: 'Lajpat Nagar, New Delhi',
    totalOrdersCount: 3,
    createdAt: new Date(Date.now() - 86400000 * 70).toISOString(),
  },
];

export const mockOrders: OrderItem[] = [
  {
    _id: 'order_01',
    jobId: 'JOB-1042',
    shopId: { _id: 'shop_01', name: 'OK-Repair Solutions', phone: '9876543210', address: { city: 'Mumbai' } },
    customerId: 'cust_01',
    customerSnapshot: { name: 'Amit Sharma', phone: '9823456781' },
    deviceType: 'mobile',
    brand: 'Apple',
    model: 'iPhone 13',
    serialOrImei: '356789123456789',
    passcodePattern: '1234',
    problemDescription: 'Shattered front OLED glass, touch erratic on upper left half. Needs display combo replacement and TrueTone calibration.',
    status: 'pending',
    assignedTechnicianId: { _id: 'tech_01', name: 'Rohan Deshmukh', phone: '9811002233' },
    cost: { estimated: 4500, final: 4500, advancePaid: 1000, due: 3500 },
    payments: [{ amount: 1000, mode: 'upi', transactionRef: 'UPI-9812491', paidAt: new Date(Date.now() - 3600000 * 2).toISOString() }],
    smsLogs: [{ type: 'order_received', status: 'sent', providerRef: 'F2S_99120', sentAt: new Date(Date.now() - 3600000 * 2).toISOString() }],
    dates: {
      receivedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
      promisedDeliveryAt: new Date(Date.now() + 3600000 * 24).toISOString(),
    },
    invoice: { invoiceNumber: 'INV-JOB-1042', issuedAt: new Date().toISOString() },
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    _id: 'order_02',
    jobId: 'JOB-1041',
    shopId: { _id: 'shop_01', name: 'OK-Repair Solutions', phone: '9876543210', address: { city: 'Mumbai' } },
    customerId: 'cust_02',
    customerSnapshot: { name: 'Pooja Patel', phone: '9712345678' },
    deviceType: 'laptop',
    brand: 'Dell',
    model: 'Inspiron 15 3511',
    serialOrImei: 'DELL-981249A',
    problemDescription: 'Laptop overheating and shutting down randomly within 15 minutes of booting. Fan makes loud grinding noise. Thermal paste dried.',
    status: 'in_progress',
    assignedTechnicianId: { _id: 'tech_02', name: 'Vikas Kadam', phone: '9822114455' },
    cost: { estimated: 2200, final: 2200, advancePaid: 500, due: 1700 },
    payments: [{ amount: 500, mode: 'cash', paidAt: new Date(Date.now() - 3600000 * 18).toISOString() }],
    smsLogs: [{ type: 'order_received', status: 'sent', providerRef: 'F2S_98941', sentAt: new Date(Date.now() - 3600000 * 18).toISOString() }],
    dates: {
      receivedAt: new Date(Date.now() - 3600000 * 18).toISOString(),
      promisedDeliveryAt: new Date(Date.now() + 3600000 * 6).toISOString(),
    },
    invoice: { invoiceNumber: 'INV-JOB-1041', issuedAt: new Date().toISOString() },
    createdAt: new Date(Date.now() - 3600000 * 18).toISOString(),
  },
  {
    _id: 'order_03',
    jobId: 'JOB-1040',
    shopId: { _id: 'shop_01', name: 'OK-Repair Solutions', phone: '9876543210', address: { city: 'Mumbai' } },
    customerId: 'cust_03',
    customerSnapshot: { name: 'Rahul Mehta', phone: '9988776655' },
    deviceType: 'mobile',
    brand: 'Samsung',
    model: 'Galaxy S22',
    serialOrImei: 'SM-S901B-128',
    problemDescription: 'Battery draining fast (drops from 80% to 20% in 1 hr). Back glass slightly lifted due to swollen lithium pouch cell.',
    status: 'repaired',
    assignedTechnicianId: { _id: 'tech_01', name: 'Rohan Deshmukh', phone: '9811002233' },
    cost: { estimated: 2800, final: 2800, advancePaid: 2800, due: 0 },
    payments: [{ amount: 2800, mode: 'upi', transactionRef: 'UPI-771829', paidAt: new Date(Date.now() - 3600000 * 8).toISOString() }],
    smsLogs: [
      { type: 'order_received', status: 'sent', sentAt: new Date(Date.now() - 3600000 * 24).toISOString() },
      { type: 'repaired', status: 'sent', sentAt: new Date(Date.now() - 3600000 * 8).toISOString() },
    ],
    dates: {
      receivedAt: new Date(Date.now() - 3600000 * 24).toISOString(),
      promisedDeliveryAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    },
    invoice: { invoiceNumber: 'INV-JOB-1040', issuedAt: new Date().toISOString() },
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    _id: 'order_04',
    jobId: 'JOB-2025',
    shopId: { _id: 'shop_02', name: 'TechZone Mobile & Laptop Care', phone: '9822334455', address: { city: 'Surat' } },
    customerId: 'cust_04',
    customerSnapshot: { name: 'Hardik Trivedi', phone: '9877665544' },
    deviceType: 'mobile',
    brand: 'OnePlus',
    model: 'OnePlus 11R',
    serialOrImei: 'OP-11R-8812',
    problemDescription: 'Water damage after heavy rain. Phone does not power on, no charging vibration. Customer urgently needs photos retrieved.',
    status: 'in_progress',
    assignedTechnicianId: { _id: 'tech_04', name: 'Jignesh Shah', phone: '9844336677' },
    cost: { estimated: 5500, final: 5500, advancePaid: 1500, due: 4000 },
    payments: [{ amount: 1500, mode: 'upi', transactionRef: 'GPAY-441029', paidAt: new Date(Date.now() - 3600000 * 12).toISOString() }],
    smsLogs: [{ type: 'order_received', status: 'sent', sentAt: new Date(Date.now() - 3600000 * 12).toISOString() }],
    dates: { receivedAt: new Date(Date.now() - 3600000 * 12).toISOString() },
    invoice: { invoiceNumber: 'INV-JOB-2025', issuedAt: new Date().toISOString() },
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    _id: 'order_05',
    jobId: 'JOB-2026',
    shopId: { _id: 'shop_02', name: 'TechZone Mobile & Laptop Care', phone: '9822334455', address: { city: 'Surat' } },
    customerId: 'cust_05',
    customerSnapshot: { name: 'Neha Singhania', phone: '9866554433' },
    deviceType: 'laptop',
    brand: 'HP',
    model: 'Pavilion Gaming 15',
    serialOrImei: 'HP-PVG-3391',
    problemDescription: 'Right hinge cracked and pulling display bezel apart. Keyboard backlight flickering intermittently.',
    status: 'parts_delayed',
    assignedTechnicianId: { _id: 'tech_05', name: 'Bhavesh Parmar', phone: '9855447788' },
    cost: { estimated: 3200, final: 3200, advancePaid: 1000, due: 2200 },
    payments: [{ amount: 1000, mode: 'cash', paidAt: new Date(Date.now() - 3600000 * 36).toISOString() }],
    smsLogs: [{ type: 'order_received', status: 'sent', sentAt: new Date(Date.now() - 3600000 * 36).toISOString() }],
    dates: { receivedAt: new Date(Date.now() - 3600000 * 36).toISOString() },
    invoice: { invoiceNumber: 'INV-JOB-2026', issuedAt: new Date().toISOString() },
    createdAt: new Date(Date.now() - 3600000 * 36).toISOString(),
  },
  {
    _id: 'order_06',
    jobId: 'JOB-3010',
    shopId: { _id: 'shop_03', name: 'iFix Tech Lab', phone: '9744112233', address: { city: 'Bengaluru' } },
    customerId: 'cust_06',
    customerSnapshot: { name: 'Sanjay Reddy', phone: '9755443322' },
    deviceType: 'tablet',
    brand: 'Apple',
    model: 'iPad Air 5th Gen (M1)',
    serialOrImei: 'DMP881290K',
    problemDescription: 'Type-C charging port loose, only charges when cable held at a specific upward angle.',
    status: 'delivered',
    assignedTechnicianId: { _id: 'tech_06', name: 'Karthik Rao', phone: '9733221100' },
    cost: { estimated: 2400, final: 2400, advancePaid: 2400, due: 0 },
    payments: [{ amount: 2400, mode: 'card', transactionRef: 'POS-Swipe-91', paidAt: new Date(Date.now() - 3600000 * 48).toISOString() }],
    smsLogs: [
      { type: 'order_received', status: 'sent', sentAt: new Date(Date.now() - 3600000 * 72).toISOString() },
      { type: 'repaired', status: 'sent', sentAt: new Date(Date.now() - 3600000 * 50).toISOString() },
      { type: 'delivered', status: 'sent', sentAt: new Date(Date.now() - 3600000 * 48).toISOString() },
    ],
    dates: {
      receivedAt: new Date(Date.now() - 3600000 * 72).toISOString(),
      deliveredAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    },
    invoice: { invoiceNumber: 'INV-JOB-3010', issuedAt: new Date().toISOString() },
    createdAt: new Date(Date.now() - 3600000 * 72).toISOString(),
  },
  {
    _id: 'order_07',
    jobId: 'JOB-4048',
    shopId: { _id: 'shop_04', name: 'RapidFix Electronics', phone: '9911223344', address: { city: 'New Delhi' } },
    customerId: 'cust_07',
    customerSnapshot: { name: 'Vikram Choudhary', phone: '9933445566' },
    deviceType: 'mobile',
    brand: 'Google',
    model: 'Pixel 7 Pro',
    serialOrImei: 'G-P7P-99120',
    problemDescription: 'Camera glass cracked over periscope telephoto lens. Photos look foggy and focus hunts continuously.',
    status: 'pending',
    assignedTechnicianId: { _id: 'tech_07', name: 'Amit Tyagi', phone: '9922334411' },
    cost: { estimated: 3800, final: 3800, advancePaid: 500, due: 3300 },
    payments: [{ amount: 500, mode: 'upi', transactionRef: 'PTM-88129', paidAt: new Date(Date.now() - 3600000 * 5).toISOString() }],
    smsLogs: [{ type: 'order_received', status: 'sent', sentAt: new Date(Date.now() - 3600000 * 5).toISOString() }],
    dates: { receivedAt: new Date(Date.now() - 3600000 * 5).toISOString() },
    invoice: { invoiceNumber: 'INV-JOB-4048', issuedAt: new Date().toISOString() },
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
];

export const mockOverview: PlatformOverview = {
  kpis: {
    totalShops: 4,
    activeShops: 4,
    proShops: 3,
    totalTechnicians: 7,
    totalCustomers: 7,
    totalOrders: 93,
    totalRevenue: 223500,
    totalDues: 29200,
    totalValue: 252700,
  },
  statusCounts: {
    pending: 14,
    in_progress: 18,
    parts_delayed: 6,
    repaired: 12,
    delivered: 43,
    canceled: 0,
  },
  recentOrders: mockOrders,
  topShops: [
    { shopId: 'shop_04', name: 'RapidFix Electronics', ownerName: 'Manoj Sharma', city: 'New Delhi', plan: 'pro', revenue: 89000, ordersCount: 34 },
    { shopId: 'shop_01', name: 'OK-Repair Solutions', ownerName: 'Sunil Verma', city: 'Mumbai', plan: 'pro', revenue: 64200, ordersCount: 28 },
    { shopId: 'shop_02', name: 'TechZone Mobile & Laptop Care', ownerName: 'Deepak Patel', city: 'Surat', plan: 'pro', revenue: 41800, ordersCount: 19 },
    { shopId: 'shop_03', name: 'iFix Tech Lab', ownerName: 'Arun Krishnan', city: 'Bengaluru', plan: 'free', revenue: 28500, ordersCount: 12 },
  ],
};

export const mockRevenueAnalytics: RevenueAnalytics = {
  summary: {
    totalRevenue: 223500,
    totalDues: 29200,
    totalGrossValue: 252700,
    ordersCount: 93,
  },
  revenueByShop: [
    { shopId: 'shop_04', shopName: 'RapidFix Electronics', ownerName: 'Manoj Sharma', plan: 'pro', revenue: 89000, dues: 11500, ordersCount: 34 },
    { shopId: 'shop_01', shopName: 'OK-Repair Solutions', ownerName: 'Sunil Verma', plan: 'pro', revenue: 64200, dues: 8400, ordersCount: 28 },
    { shopId: 'shop_02', shopName: 'TechZone Mobile & Laptop Care', ownerName: 'Deepak Patel', plan: 'pro', revenue: 41800, dues: 6200, ordersCount: 19 },
    { shopId: 'shop_03', shopName: 'iFix Tech Lab', ownerName: 'Arun Krishnan', plan: 'free', revenue: 28500, dues: 3100, ordersCount: 12 },
  ],
  paymentsByMode: [
    { _id: 'upi', totalAmount: 142000, count: 58 },
    { _id: 'cash', totalAmount: 51500, count: 22 },
    { _id: 'card', totalAmount: 22000, count: 9 },
    { _id: 'online', totalAmount: 8000, count: 4 },
  ],
  statusFinancials: [
    { _id: 'delivered', revenue: 145000, dues: 0, count: 43 },
    { _id: 'repaired', revenue: 32000, dues: 4500, count: 12 },
    { _id: 'in_progress', revenue: 27500, dues: 14200, count: 18 },
    { _id: 'pending', revenue: 12000, dues: 8500, count: 14 },
    { _id: 'parts_delayed', revenue: 7000, dues: 2000, count: 6 },
  ],
};

export const mockNotifications: NotificationItem[] = [
  {
    _id: 'notif_01',
    title: '📢 Diwali Bulk Spare Parts Special Discount',
    message: 'All verified repair centers receive an extra 15% discount on iPhone 13/14 OLED combos and Samsung display panels ordered through partner vendors this week.',
    type: 'broadcast',
    priority: 'promo',
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    _id: 'notif_02',
    title: '⚡ Fast2SMS Gateway DLT Template Update',
    message: 'TRAI regulatory template updates will take effect tonight at 12:00 AM. Simulated delivery will continue uninterrupted.',
    type: 'broadcast',
    priority: 'info',
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    _id: 'notif_03',
    title: '⚠️ Uncollected Due Balance Alert',
    message: 'Please review pending customer pickups. Over ₹8,400 in uncollected dues is pending collection for jobs completed more than 48 hours ago.',
    type: 'direct',
    targetShopId: { _id: 'shop_01', name: 'OK-Repair Solutions', phone: '9876543210' },
    priority: 'warning',
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
  },
];

